# Generated by Django 4.1.2 on 2022-12-01 03:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comorbidity_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidity_type_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='meal_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('k', models.FloatField()),
                ('na', models.FloatField()),
                ('protein', models.FloatField()),
                ('phosphate', models.FloatField()),
                ('water', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('birth_date', models.DateField(default=datetime.datetime.today)),
                ('gender', models.CharField(max_length=1)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('personname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=130)),
                ('comorbidity_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homepages.comorbidity_type')),
            ],
        ),
        migrations.CreateModel(
            name='daily_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homepages.meal_type')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepages.person')),
                ('substance', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='homepages.substance')),
            ],
        ),
    ]
