# Generated by Django 4.1.2 on 2022-11-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='username',
            new_name='personname',
        ),
    ]
